# Generated by Django 5.0.6 on 2024-06-02 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_tool', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('done', 'Done'), ('pending', 'Pending')], max_length=20),
        ),
    ]
